#Para crear node_modules, instalar nuevas librerias, etc

version: "3.8"


services:

  node_install:
    container_name: node_install
    image: "node:14"
    working_dir: /home/node/app
    volumes:
      - ./app/:/home/node/app   #Integra node_modules dentro de la carpeta app


    command: sh -c "npm install"